languageCode = "zh-CN"
title = "中国人民大学统计学院校友会"
theme = "crab"
baseurl = "/"

[params]
description = "人大统计校友信息平台"

[permalinks]
post  = "/post/:year/:month/:slug/"

[taxonomies]
tags = "tags"

[[menu.main]]
weight = 1
name = "首页"
url = "/"

[[menu.main]]
weight = 2
name = "关于"
url = "/about/"

[[menu.main]]
weight = 3
name = "章程"
url = "/constitution/"

[[menu.main]]
weight = 4
name = "动态"
url = "/post/"
